loop_counter_factor: -1.0
debug_backdoor: true
biped_controller:
   delta_T: 0.005
   ft_sensor_z: 0.04

com_stabilizer:
   ds_x_p: 0.8
   ds_y_p: 0.6
   ss_x_p: 1.0
   ss_y_p: 1.0
  
zmp_solver:
   z_lipm: 0.7


